"$schema" = 'https://starship.rs/config-schema.json'

format = """$directory$character"""
right_format = "$git_branch$git_status$time"

[character]
success_symbol = "[•](bold green)"
error_symbol = "[×](bold red)"
vimcmd_symbol = "[«](bold blue)"

[time]
disabled = false
time_format = "%d%b%H:%M"
format = "[$time](dimmed fg:251)"

[git_branch]
# remove the word 'on'
format = "[$symbol$branch(:$remote_branch)]($style) "

[git_status]
# remove the brackets surrounding the status
format = '([$all_status$ahead_behind]($style) )'
